# conda env create -f environment.yml
# conda env update --file environment.yml --prune
name: 'vancrime'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - pip
  - dash
  - flask
  - pandas
  - numpy
  - pip:
      - dash_bootstrap_components
      - dash_bootstrap_templates